sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - DISPLAY=:99.0
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install: true
script:
- mvn clean verify
notifications:
  email:
  - jeffmaury@jeffmaury.com
